# Site settings
title: Paul A. Strassmann
email: paul@strassmann.com
description: Strassmann, Inc.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.strassmann.com" # the base hostname & protocol for your site

timezone: America/New_York
exclude: ['Gemfile', 'Gemfile.lock']

collections:
  afcea: {output: true, permalink: 'pubs/afcea/:name.html'}
  baseline: {output: true, permalink: 'pubs/baseline/:name.html'}
  computerworld: {output: true, permalink: 'pubs/cw/:name.html'}
  idc: {output: true, permalink: 'pubs/idc/:name.html'}

defaults:
- scope: {path: pubs}
  values: {author: Paul A. Strassmann, layout: post}

