# Site settings
title: Strassmann, Inc.
email: steve@strassmann.com
description: > # this means to ignore newlines until "baseurl:"
  Strassmann, Inc.
baseurl: "/pas" # the subpath of your site, e.g. /blog/
url: "http://strassmann.com" # the base hostname & protocol for your site
#twitter_username: ostraz
#github_username:  straz

# Build settings
#markdown: kramdown

timezone: America/New_York
