<?php

require("utils.php");

$title = "Global Knowledge Power";
$date = "June, 2000";
$pdate = "6-1-2000";
$coverart = "0600-cover.jpg";
$subhead = "Further accumulation and consolidation of 
knowledge is likely to exacerbate global conflicts.";

$body = "

<p>Last month (\"Knowledge Monopoly,\" May 2000 <I>KMM)</I> I estimated the
distribution of Knowledge Capital in the U.S. economy. I found that only 84 U.S.
firms, each with Knowledge Capital in excess of $20 billion, accounted for 83
percent of all of the Knowledge Capital available to 7,288 publicly listed
corporations. The fact that only 1.2 percent of all those firms own that much
clearly indicates a concentration of economic power. </p>

<p> Such a skewed
distribution of assets will have much greater consequences in an
information-based economy than in an economy that depends on natural resources or
financial capital. It is widely accepted that Knowledge Capital exhibits
\"increasing economies of scale,\" a measure that economists use to describe
investments whose marginal productivity improves as it grows. Thus, expansion
unconstrained by competition will always favor further concentration of economic
power by any company that succeeds in occupying an early leading position in any
market. </p>

<p> In contrast to the inherent winner-take-all characteristics of
knowledge-based marketing, enterprises that continue to depend on natural
resources, labor and financial capital will remain limited by the economic laws
of diminishing returns, or decreasing economies of scale. Such firms (or
countries) will see costs rise and prices decline; these factors will manifest
themselves as declining productivity, which was a characteristic of the U.S.
economy for much of the period from 1965 to 1995 and is now endemic to most other
countries in the world. </p>

<p>

<B>The global situation</B><br>
	Although in future articles I intend to focus on metrics that compare the
financial structures of U.S. corporations--such as contrasting the different
financial structures of U.S. Steel, General Motors and Intel--I want to take time
now to examine some metrics that reveal analytic insights about the statistics
that are starting to shape the ongoing debates about multinationalism and
globalization. </p>

<p> Much of the prevailing rhetoric by proponents of expanding
world trade ignores the rapid approach of confrontations between the rising
economic power based on knowledge capital and the increasing vulnerability of
those who own other forms of assets. Controversies about topics such as
deforestation, ecological damage, genetic engineering and the debts of
underdeveloped countries are certainly relevant, but they block an appreciation
of the underlying fundamentals. These causes can be summarized as follows.
</p>

<p> Concentration of economic power, which I have already shown as prevailing
in the United States, is even more pronounced on a global scale. Only six
countries, which together are home to 11 percent of the total global population
of 5.9 billion people, generate 62 percent of the global gross national product
(GNP) of $29 trillion. The U.S. accounted for 27 percent of the world's GNP in
1998; five others--Japan, Germany, the United Kingdom, France and Italy--together
accounted for 35 percent. </p>

<p> Most of the world's working population does not
participate in the global economy. The 19,691 publicly listed corporations
generate $24 trillion of revenue, which accounts for most of the world's GNP.
Almost half of those companies originate in the U.S. </p>

<p> The net total of the
Knowledge Capital owned by the world's 19,691 listed corporations is about $12
trillion; the U.S. owns 57 percent of that total. The $12 trillion total is
generated by only 94 million employees. </p>

<p> The consequences of these
disparities are far-ranging and likely to influence the course of international
relations for several generations. Although underdeveloped countries will
continue to rush into industrialization, their relative economic standings may
not improve because knowledge-based economies will control global markets. As a
result, local political elites, who traditionally have controlled national
information structures, will agitate against the intrusion of international
corporations or organizations. Such resistance could take the form of direct
political interference or possibly deteriorate into traditional and/or
information-based forms of warfare. In the same way that the transition from
land-based ownership to capital-based industrialization (which much of the world
has not yet completed) shaped most historical developments since the 15th
century, equally painful transitions will take place at accelerated speed in the
years to come. The difference is that now the desire and the means for acquiring
knowledge are pervasive; the world population is becoming aware that knowledge is
the ultimate source of power. The intrinsic tendencies that favor concentration
of Knowledge Capital will have to be tempered by the political realities of
universal dissatisfaction that this imbalance will generate. Politics, not
technology, is likely to dictate further progress in the globalization of
knowledge management. </p>

";

 $article = array ( 
  title => "$title",
  date => "$date",
  pdate => "$pdate",
  coverart => "$coverart",
  subhead => "$subhead",
  body => "$body");

echo show_km_article ($article);

?>